### ISSUE TITLE
Raw response return in utils / make_requests

### ISSUE THREAD

**Issue by hemidactylus** [datastax/astrapy#27]
In:
```
    try:
        if return_type == "json":
            return r.json()
        else:
            return r
```
shouldn't it be ` r.text` at the end?

**Comment by erichare** [comment]
@hemidactylus the reason for this.... is for reasons that i'm not quite sure of. It was in the existing package and i just left it. For create and terminate database, we return:

```
    def create_database(self, database_definition=None):
        r = self._ops_request(
            method=http_methods.POST,
            path="/databases",
            json_data=database_definition,
            return_type="response"
        )

        if r.status_code == 201:
            return {"id": r.headers["Location"]}

        return None

    def terminate_database(self, database=""):
        r = self._ops_request(
            method=http_methods.POST,
            path=f"/databases/{database}/terminate",
            return_type="response"
        )

        if r.status_code == 202:
            return database

        return None
```

I'm wondering if actually we just always want to return the response object, so any downstream function can process it, the status code, etc as needed

**Comment by erichare** [comment]
@hemidactylus - i've cleaned this up. I think it's best that we return the raw response. The reason being is that in theory each api call can have different behavior depending on the status code, etc. Right now we don't carefully check that very often, but we can and should. So that utility function will return the raw response - we can extract the json data, the text, the status_code, and any other property of it. I think that'll keep things more extensible.
